### PR TITLE
Endstop documentation

### PR DESCRIPTION
**Pull request by Sineos**
I thought the new Endstop setting / filtering could use some warm words in the documentation.

This is not meant to be scientifically comprehensive but to give the regular user an idea about the topic. Please review @thinkyhead and @ejtagle

### CODE REVIEW

**Comment by Sineos** [comment]
Add pdf version for easier review
[Endstops _ Marlin Firmware.pdf](https://github.com/MarlinFirmware/MarlinDocumentation/files/2032762/Endstops._.Marlin.Firmware.pdf)

**Comment by ejtagle** [comment]
@Sineos : The explanation is nearly perfect 👍 -- Thanks for such valuable contribution!

**Comment by thinkyhead** [comment]
Thanks @Sineos — It might be good to make the title  "Endstops" and start with an introduction explaining what endstops are and how they work, including images and descriptions of the different types of endstops we commonly use. That would make the page fit better into the "Features" section, while still providing useful guidance on how to troubleshoot them.

Also, for future use, let's add the "hardware" category:
```
category: [ features, hardware ]
```

**Comment by Sineos** [comment]
Well, endstops is a big playing ground, nevertheless, here is my fist take on it. Also:
- Added hardware section
- Moved boards to hardware section
- Moved TMC to hardware section

`category: [ features, hardware ]`
It does not seem to work to add multiple categories to an entry. At least the navigation structure only follows the folder structure but not the assigned categories. Tried to look into it but unfortunately this is over my meager coding skills.

**Comment by thinkyhead** [comment]
> It does not seem to work to add multiple categories to an entry

Weird. It works for me.

Pages that had the "features" category misspelled as "feature" were **not** showing up in the "Marlin features" submenu, but then after I changed some to "features" and others to "[ features, etc ]" they **did** show up there, and on the "[All documents](http://marlinfw.org/meta/features/)" page too.

**Comment by Sineos** [comment]
> "Hardware" doesn't have its own sub-menu at this time. I'll need to add it to the categories section of _config.yml.

My PR already adds this category.

> Weird. It works for me.

E.g. `category: [ development, hardware ]` in `boards.md`, shows up in the Development category if I put it in the `_development `folder or in the Hardware category if put in the `_hardware` folder but not in both categories. 
Maybe a local issue in my jekyll install. If it works for the live site everything is fine.

With your changes to the master branch, how can I pull them in my PR branch without loosing my changes?

Side note:
Something I could not fix as well: If I use the block quote markdown `>`  the font size in the block is different to the rest of the document.

**Comment by thinkyhead** [comment]
> With your changes to the master branch, how can I pull them in my PR branch without losing my changes?

You're right that it's a hassle to add a new category, so let's skip that.

I'll rebase this work as it is and merge it, and then you'll need to do some git magic to apply your changes to the updated `master` branch.

After this is merged, to bring in your new changes you'll need to do this from the Git console…
```
git checkout master -b my_endstops_work
git fetch upstream
git checkout master
git reset --hard upstream/master
git push -f origin master
git diff HEAD my_endstops_work | git apply
```
…and then "cherry-pick" the changes you want to keep using GitHub Desktop's handy GUI, commit and push as usual, and then make a new PR. Just your endstops.md changes matter. If you did anything else, like move items to a `_hardware` subfolder (which I attempted earlier), just discard those changes for now.

**Comment by thinkyhead** [comment]
Looks like you had better luck than me moving things around. Good!

> With your changes to the master branch, how can I pull them in my PR branch without losing my changes?

Git merge wouldn't work too well since I rebased `master`. So…

After I merge this, just publish your latest changes to a new branch in your fork, then notify me and I'll pull everything in and merge your changes. Then I'll just tell you what I had to do, and whether it was tricky or easy.

**Comment by thinkyhead** [comment]
Note:
```
ERROR `/docs/hardware/assets/images/docs/hardware/tmc_drivers/FYSETC_tmc2130._SPI.jpg' not found.
```

**Comment by thinkyhead** [comment]
Note:
```
- ./_site/tools/u8glib/converter.html
  *  internally linking to /meta/hardware/, which does not exist (line 41)
     <a href="/meta/hardware/"> All documents </a>
```

**Pull request merged**
