### PR TITLE
Detail how to disable extra debug output

### PR DESCRIPTION
**Pull request by fiveangle**
M111 S0 to Disable extra debug output.

If the "DEBUGGING" for "Name" column is technically incorrect, change to "_default_"

### CODE REVIEW

**Comment by thinkyhead** [comment]
I merged too soon. These values are combined together. They all have to be non-zero. Adding or OR'ing zero has no effect on the other bits that are already set, so `DISABLE` is not a thing.

**Comment by fiveangle** [comment]
Did you read my comment.  I understand that, but there is no documentation on how to disable it for the layment who are not programmers.  I don't care how you do it, but make the questions stop :)

**Comment by fiveangle** [comment]
So does Travis build fail because it requires you to hand-enter a new key for every change ?

**Comment by thinkyhead** [comment]
I think it might now be building successfully due to a recent patch. Keep an eye on this space.

**Pull request merged**
