### PR TITLE
updates

### PR DESCRIPTION
**Pull request by boelle**
Added re-arm+Ramps as default platform

removed skeinforge as download link no longer work

made all links https

added warning on cura

### CODE REVIEW

**Comment by jonathanweinberg** [comment]
This stalled or waiting on something @thinkyhead ?

**Comment by thinkyhead** [comment]
@jonathanweinberg — We don't just merge things right away, and this needs further editing.

**Comment by jonathanweinberg** [comment]
Great. So it is waiting on something. It’s waiting on editing. We should talk about getting aggressive around the use of tags on issues/pulls/convos and such.

It really helps a team and others understand what things are in what state/stage.

**Comment by thinkyhead** [comment]
One of these days I will have more time to work on the documentation. But right now all my time is taken up with merging PRs and trying to get Marlin 2.0 in shape for a beta release. Cheers!

**Comment by thinkyhead** [comment]
Merging parts of this now…

**Pull request closed without merging**
