### PR TITLE
Update k-factor generator

### PR DESCRIPTION
**Pull request by Sineos**
- Add option to rotate the pattern
- Add option to print anchor frame
- Add alternate test pattern
- Add option to modify test line spacing
- Improve bed size sanity checks
- Add css and some html clean up
- Improve speed toggling
- Increase priming extrusion
- Double priming length
- Fix acceleration
- Add nozzle prime toggle
- Add prime extrusion multiplier
- Add dwell time before pattern start to bleed off residual nozzle pressure
- Add option to set the test line length for slow and fast speeds

### CODE REVIEW

**Comment by thinkyhead** [comment]
I had to patch the script due to a bug. The `MM_S` checkbox was applied in reverse. I ended up hiding the element because Marlin doesn't use `MM_S` feedrates.

Some other tweaks were made also. I will get this merged with the updated tool soon.

**Comment by Sineos** [comment]
> I ended up hiding the element because Marlin doesn't use MM_S feedrates.

The script transforms the feedrates to mm/min. It is just for the user to choose which notation he prefer. I personally prefer mm/s over mm/min.

Pushed a small update to fix the html number field steps.

Merry Christmas :-)

**Comment by thinkyhead** [comment]
> Add option for round beds

Not needed. `LIN_ADVANCE` only works on Cartesian due to technical limitations.

> The script transforms the feedrates to mm/min. It is just for the user to choose which notation he prefer. I personally prefer mm/s over mm/min.

If the intent is for the user to alter the values in the fields, then checking / unchecking the box should convert the values in the fields in-place. It was unclear from the page text or the field that it changed the meanings of the other fields.

**Comment by Sineos** [comment]
> If the intent is for the user to alter the values in the fields, then checking / unchecking the box should convert the values in the fields in-place. It was unclear from the page text or the field that it changed the meanings of the other fields.

With the PR the conversion is done in place. For the script itself the movement is always calculated as mm/min.

> Not needed. LIN_ADVANCE only works on Cartesian due to technical limitations.

I will remove it.

**Comment by Sineos** [comment]
Round bed is removed. Some additional clean up.

**Comment by thinkyhead** [comment]
Ok, pulled in all changes. Thanks!

**Comment by stoianchoo** [comment]
"Patch k-factor" eb12a5c renames the call for k-factor.js to K-factor.js which results in 404 error. Thus the generator does not work for me on Chrome 63  :(

**Pull request closed without merging**
