### PR TITLE
📝 Overhaul README

### PR DESCRIPTION
**Pull request by thisiskeithb**
As the title states, completely overhaul the repository README.

The main focus (and entire reason I started down this path) was to add *tested* and *working* Ruby & Jekyll install procedures for local development/preview since the current instructions were woefully out of date and did not work.

This involved setting up new VMs for Windows 10, macOS 12.7.6 (limited by my hardware), & Ubuntu 24.04 LTS and validating each step to work out any bugs. After working out the steps & commands, VMs were reset to a fresh state & the updated Ruby/Jekyll install process was verified to work without issue.

H/t to @ellensp for being a sounding board while I bashed my head against the wall working through these issues.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
...and of course [GitHub Pages dependency versions](https://pages.github.com/versions/) were just updated yesterday to recommend Ruby 3.3.4 and Jekyll 3.10.0.

We still have an issue with our site being incompatible with Ruby 3.x, so it'll probably be a while before using these new versions.

**Comment by thisiskeithb** [comment]
All of these changes will work as-is, but @ellensp found a way to get everything building with current versions of Ruby & Jekyll on Ubuntu, so I will mark this as a draft PR until I can test them on clean Windows & macOS VMs and verify that we can use updated versions on all platforms.

**Comment by thisiskeithb** [comment]
This PR now relies on https://github.com/MarlinFirmware/MarlinDocumentation/pull/579 since I've confirmed that everything builds in clean installs of Ubuntu 24.04 LTS, Windows 10, and macOS Monterey 12.7.5 (limited by my hardware) using Jekyll 3.10.0 & Ruby 3.3.4. Instructions have been updated accordingly.

I've also added Ubuntu instructions based on @ellensp's tips.

**Comment by thinkyhead** [comment]
Homebrew is a popular macOS package manager, but I prefer to use MacPorts, and I based my earlier instructions with consideration for both the MacPorts package manager and Homebrew. It would be good to retain the instructions for both.

**Comment by thisiskeithb** [comment]
> It would be good to retain the instructions for both.

Noted. I'll verify the MacPorts instructions still work & adjust as necessary.

**Comment by thisiskeithb** [comment]
> I'll verify the MacPorts instructions still work & adjust as necessary.

We didn't exactly have complete MacPorts installation instructions before, but I tested & confirmed that the updated instructions work.

I vaguely remember something about paths being different if you're on an Arm-based Mac, so I need to double-check that and potentially split things up further.

**Pull request merged**
