### PR TITLE
Added Cura implementation instruction to M493

### PR DESCRIPTION
**Pull request by dsdanielko**
Follow up to last pr

### CODE REVIEW

**Comment by thinkyhead** [comment]
Does Cora no longer require the "Post Processing Plugin"? I noticed it does not exist on the Cura Marketplace.

**Comment by thisiskeithb** [comment]
> Does Cura no longer require the "Post Processing Plugin"? I noticed it does not exist on the Cura Marketplace.

You can get to it from Marketplace -> Settings (⚙️) -> Manage Packages

Post Processing Plugin

**Comment by dsdanielko** [comment]
huh it looks to me like the plugin is now auto-installed. i can take out that line if its better, but i definitely remember having to install it from the marketplace only a couple of versions ago

**Comment by dsdanielko** [comment]
Ok I've changed the line about post processing plugin. Please review

**Pull request merged**
