### PR TITLE
[DOC] Add M997 Restart Page

### PR DESCRIPTION
**Pull request by reloxx13**
Add page for `M997 Restart` gcode command

New:
grafik

https://github.com/MarlinFirmware/Marlin/pull/13281
https://github.com/MarlinFirmware/Marlin/pull/15209
https://github.com/MarlinFirmware/Marlin/pull/7768#issuecomment-349704204
https://reprap.org/wiki/G-code#M997:_Perform_in-application_firmware_update

### CODE REVIEW

**Comment by reloxx13** [comment]
Unsure about flag `since: 2.0.0` ?

**Comment by p3p** [comment]
M997 only restarts because the LPC176x (and now some STMF1) only require restarted to flash the firmware.bin file already copied to the sd card, the command is actually `Perform in-application firmware update` as stated in the rep-rap gcode list.

The flag is made available for platforms that have more than one firmware that could be flashed, doesn't quite adhere to the standard set in the doc as they used a set.

For some future implementation this command could do much more than just restarting.

**Comment by shitcreek** [comment]
LMK when this is ready to be merged

**Comment by shitcreek** [comment]
@reloxx13 is this ready to be merged now?

**Comment by reloxx13** [comment]
heya,
from my side, yes. i dunno if @p3p wanted (or want me) to add sth.

**Comment by p3p** [comment]
I was trying to explain that M997 isn't a Restart command ^^ thats just what it does on platofrms where restarting triggers a firmware flash. So the naming is a bit off.

**Comment by reloxx13** [comment]
> I was trying to explain that M997 isn't a Restart command ^^ that's just what it does on platforms where restarting triggers a firmware flash. So the naming is a bit off.

it executes eg.
`NVIC_SystemReset();` or `nvic_sys_reset();`

Updating firmware is "a bonus" since it will always update after a restart if there is a firmware file on sd and only if it is supported. There may boards which does not flash on boot but still could restart.

That was the reason i called it "Restart".

**Comment by p3p** [comment]
> Updating firmware is "a bonus" since some boards will always update after a restart if there is a firmware file on sd and only if it is supported by the bootloader.

No that's the wrong way round, as the reprap standard states `M997` flashes the firmware, it's the restart that is just a function of performing that action.

I realise that the implementation I added does just restart, but again that is only because it is necessary to perform the firmware flash on those platforms.

In my opinion the Marlin documentation should state that `M997` performs a firmware update, mentioning that on some platforms (LPC176x), or specific boards in the STM32 case, this is done by performing a restart and letting the bootloader take care of it.

**Comment by reloxx13** [comment]
@p3p pls review :)

grafik

**Comment by p3p** [comment]
looks good, although `LPC176x` is a platform not a board and `STM32` covers 3 separate platforms, .. I'm not sure how many STM32 boards actually support this.

**Comment by shitcreek** [comment]
I think it's good enough. LMK if there needs to be any correction.

**Pull request merged**
