### PR TITLE
add Update PR section to "Contributing Code with Pull Requests"

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
Appended update PR section to exiting doc.

Added 18 new images.

Deleted the Corel autosave folder.  It shouldn't have been included in the original release.

All deletions are due to deleting the Corel folder

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
All the Travis errors are with code in the Master Branch.  Do you want me to try to fix them?

**Comment by Roxy-3D** [comment]
Please do...    But I guess that causes this question to be asked:  How do we turn off Travis for this branch but not affect the main branch?

**Comment by Bob-the-Kuhn** [comment]
Made a change to the configuration.md file - deleted the mfg link for RA_CONTROL_PANEL 

RA_CONTROL_PANEL - mfg link no longer valid
http://www.elefu.com/index.php?route=product/product&product_id=53

**Comment by Bob-the-Kuhn** [comment]
Squashed all the commits.

No known open items/changes/issues for this PR.

**Comment by thinkyhead** [comment]
Beautiful, thank you! More documentation is always welcome.

**Pull request merged**
