### PR TITLE
Rename "Starting Temperature" to "Ambient Starting Temperature"

### PR DESCRIPTION
**Pull request by StevilKnevil**
Used `Ta` to represent ambient "starting temperature" (rather than `Ts` for "starting temperature") to avoid confusion with the variables in the "Model Details & Tuning Algorithm" sections, where `Ta` is "ambient temperature" and `Ts` is "sensor temperature".

### CODE REVIEW

**Comment by tombrazier** [comment]
Avoiding that confusion with Ts and sensor temperature is a very good idea. Thanks for pointing it out.

Re-reading the procedure, the value Ts (or as you suggest, Ta) has two different roles. In the sensor responsiveness calculation it is the temperature the hotend was at when the calibration began, i.e. T(t) at time t=0. In the ambient transfer coefficient calculation it is properly the ambient temperature, Ta. Since the test is constructed to make these two values the same, I think Ta is probably the best name but it may leave some confused as to why ambient temperature is used in calculating sensor responsiveness. I like the wording "ambient starting temperature", it helps to defuse this latter confusion.

**Comment by tombrazier** [comment]
@thinkyhead @thisiskeithb I like this PR.

**Comment by thisiskeithb** [comment]
Works for me, but I don’t have merge powers 🙂

**Comment by tombrazier** [comment]
But you do have label powers.

**Comment by tombrazier** [comment]
Why delete and close Stevil?

**Comment by StevilKnevil** [comment]
My bad! I renamed the source branch to something more sensible, but that resulted in a closed PR! I've reinstated :)

**Comment by tombrazier** [comment]
Ah, well at least it wasn't something I said then :)

**Pull request merged**
