### PR TITLE
retract/recover gcode tuning script

### PR DESCRIPTION
**Pull request by petaflot**
follow-up to https://github.com/MarlinFirmware/MarlinDocumentation/pull/562#issuecomment-2271483980

URLs were fixed

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This PR has conflicts & changes 24 files. Can you rebase/start with a clean branch?

**Comment by thisiskeithb** [comment]
I've rebased this PR to bring it up to date with current `master` & resolved merge conflicts, so please update your local copy with the following before pushing additional commits:

```shell
git checkout jczd
git fetch origin
git reset --hard origin/jczd
```

**Comment by petaflot** [comment]
> I've rebased this PR to bring it up to date with current `master` & resolved merge conflicts, so please update your local copy with the following before pushing additional commits:
> 
> ```shell
> git checkout jczd
> git fetch origin
> git reset --hard origin/jczd
> ```

thanks a lot, @thisiskeithb 

unfortunately I have a problem here...
```
$ git reset --hard origin/jczd
fatal: ambiguous argument 'origin/jczd': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
maybe you can help (again)?

**Comment by petaflot** [comment]
ps: I fully agree on the changes you have made :-)

**Comment by thisiskeithb** [comment]
> maybe you can help (again)?

If you were able to run the previous two commands, then `git reset --hard origin/jczd` should have worked. I just tested it on my machine (using the `petaflot` remote instead of `origin`) and it worked 🤷

**Comment by thisiskeithb** [comment]
@petaflot: It looks like you've undone some upstream changes & merged in changes from your other PR: https://github.com/MarlinFirmware/MarlinDocumentation/pull/543, so this ends up changing a lot more than a single file.

**Pull request merged**
