### PR TITLE
fix k-factor.js

### PR DESCRIPTION
**Pull request by Sineos**
Fix typo. Case sensitive. Stupid windows

### CODE REVIEW

**Comment by ikarisan** [comment]
Now the generator does NOT work even under "Linux Mint 18" and Firefox 47!

**Comment by fiveangle** [comment]
Agreed.  Either change the filename to be capital "K" in the URL or fix the script to use the all lower-case filename.  This has nothing to do with Windows, but has to do with the fact that "K" != "k" :)

**Comment by Sineos** [comment]
Oh, it has something to do with windows. In that sense that windows is case insensitive towards filenames. If it was case sensitive I had noticed the error during my tests. Error is coming from a batch search and replace and I didn't notice it because windows does not care.

**Comment by Sineos** [comment]
Thanks :-)

**Pull request merged**
