### PR TITLE
Adds the G-Code collection

### PR DESCRIPTION
**Pull request by jbrazio**
Work in progress..

wip

### CODE REVIEW

**Comment by thinkyhead** [comment]
Wow, this is really cool stuff. Not only gives us good documentation, it's structured so we could use it to produce other output (e.g., PDF). Looking forward to finishing up all these GCodes – dozens…

**Comment by jbrazio** [comment]
@thinkyhead 
I've finished the G-Codes.. these are not the problem, but when I look at the M-Codes.. lol

**Comment by thinkyhead** [comment]
I wish we could save some vertical space somehow. The arguments take up a lot. Maybe we can have the argument part (with datatype) on the left (as a table cell?) and the description on the right of that (another table cell?). As a "Usage" line, we could consider imitating the Unix command usage style. An optional argument appear inside braces — `[S<bool>]` — while parameters taking options show them with bars — `G29 S<0|1|2|3>` — or something like that.

If we can imagine, what would it be like to type in a console, as if they were Unix commands…?
```
$ G1 --help

Usage: G1 [X<pos>] [Y<pos>] [Z<pos>] [E<pos>] [F<units/min>]

G1 moves the current tool to the given position (XYZE) at the given feed rate (F). The given feed rate applies to future movement commands.
```
Almost want to make a GCode console that works from the command-line… because Unix.

**Comment by jbrazio** [comment]
@thinkyhead like this ?
untitled

The little red dot is my mouse pointer, I'm demonstrating the on:hover() functionality.
This more or less makes redundant the argument list we had before, what do you think ?

**Comment by jbrazio** [comment]
It's now looking like this [on my dev branch].

untitled

**Comment by thinkyhead** [comment]
I like the hover behavior, although it does rely on the user to "accidentally" discover it. Does that information show up in a normal list when you use the "@media print" style sheet? Otherwise the information won't appear when saving the page as PDF or printing it out.

**Comment by jbrazio** [comment]
I will build a table bellow the Usage and before the Examples section.

**Pull request merged**
