### PR TITLE
Pinda v2

### PR DESCRIPTION
**Pull request by tompe-proj**
Added some documentation for following merge request:
[https://github.com/MarlinFirmware/Marlin/pull/16293](url)

English is not my native language but I think it should be somehow understandable.
Feel free to modify any files as needed.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks good, thanks!

**Comment by 3d-gussner** [comment]
Great can you please update RepRap Gcode wiki as well?

**Comment by thinkyhead** [comment]
If one of you does not, it will fall to me, and I am overtaxed right now.

**Comment by 3d-gussner** [comment]
@thinkyhead I can do it if @tompe-proj don't mind. You are a busy guy and if i can help with that kind of stuff just ping me.

**Comment by tompe-proj** [comment]
@3d-gussner if you have the time feel free to update the RepRap Wiki yourself, you can copy from the Marlin Wiki I already updated.
I will only find time on weekend again, so if it isn't updated until then I will do it myself.

**Comment by 3d-gussner** [comment]
@tompe-proj @thinkyhead I will update the RepRap Wiki ... with a note that it is in Marlin bugfix-2.x

**Comment by 3d-gussner** [comment]
Just updated [RepRap G code Wiki G76](https://reprap.org/wiki/G-code#G76:_PINDA_probe_temperature_calibration)

Isn't M871 similar to [M861](https://reprap.org/wiki/G-code#M861_Set_Probe_Thermal_Compensation)??

**Comment by tompe-proj** [comment]
@3d-gussner Thank you.
You are right, I actually intended to use M861 at first, but then found in gcode.cpp that it is already used for _I2C_POSITION_ENCODERS_ (Report encoder module status).

**Comment by 3d-gussner** [comment]
@tompe-proj Thanks, checked Marlin gcode.cpp and you are right there is M860-869 defined. But no entry on Marlin gcode documentation and no entry on RepRap Gcode Wiki. So no blame on Prusa this time 😄 

Did you check Prusa [M860](https://reprap.org/wiki/G-code#M860_Wait_for_Probe_Temperature) is that something you would like to implement as well?

I will ask Prusa if they are willing to change their M860 and M861 to M870 and M871.
If everyone agrees I will update the RepRap Gocde Wiki. I may even try to update Marlin Gcode documentation.

@thinkyhead Is it okay? Should i review the documentation of the gcodes in Marlin vs Marlin/RepRap documentation, and update them?

Not sure which Documentation is leading but this is now the second time in short time where we have collisions of Gcode.
I would like to get all three big 3d printing firmware to use the same Gcodes for same/similar tasks/functions.

**Comment by tompe-proj** [comment]
@3d-gussner I'm currently quite busy but I think I can implement that when it gets better (its not too complex from what I saw), maybe I'll even play around with the M45 command then.

**Comment by 3d-gussner** [comment]
@thinkyhead I talked to Prusa and their proposal is that Marlin changes the `I2C_POSITION_ENCODERS` M860-M869 to M870-879 as it isn't documented/allocated neither in Marlin nor in RepRap Gcode Wiki Documentation.

Prusa M860 and M861 have been kindly added to RepRap Gcode wiki by @t0hinkyhead on 19th Oct 2019 and have been updated by me and Dc42 on 4th Nov/ 8th Dec 2019.

I found `Marlin\src\feature\I2CPositionEncoder.cpp` and it can be activated in `Configuration_adv.h`.

So what are we doing?

I am just a middle man so please don't be mad at me ;-)

**Comment by thinkyhead** [comment]
> there is M860-869 defined. But no entry on Marlin gcode documentation and no entry on RepRap Gcode Wik

I'm happy to change these codes to anything at all. They were introduced something like 3 years ago and at that time there was less focus on follow-up. They didn't get into the Marlin docs because the g-codes don't have their own files with nice g-codey names.

The SCARA calibration codes `M360`-`M364` can also be moved if they're in the way of better things.

If you happen to see any other missing codes please point them out.

**Pull request merged**
