### PR TITLE
Update lin_advance.md

### PR DESCRIPTION
**Pull request by zonalimitatore**
Add italian language

### CODE REVIEW

**Comment by thinkyhead** [comment]
If we make the site multi-lingual, translations like this will have to be done by some other method.

**Comment by zonalimitatore** [comment]
???
I've click on "improve this page",and do the translation
What kind of other method mean?

A people spend time for make Marlin for all,and my translate was be close...bah.

**Comment by thinkyhead** [comment]
> What kind of other method mean?

It means that either we need to provide a button that translates the _entire site_ to a variety of languages, or we must keep it to English only.

We simply don't have the time, help, or resources to make the entire site properly multi-lingual or to maintain other languages as we make changes to the English versions.

Moreover, this PR destroys the English version of the page.

**Comment by zonalimitatore** [comment]
And there is a button in t top of the page. Before some other people spend time,delete the link in the site.....

**Comment by thinkyhead** [comment]
Thanks, we'll look at that. The site is auto-generated by Jekyll, and we have not completely customized the boilerplate system that we started with to our preferences.

**Pull request closed without merging**
