### PR TITLE
Building for Re-ARM using PlatformIO

### PR DESCRIPTION
**Pull request by ModMike**
Installing Marlin 2.0 on a Panucatt Re-Arm board and others using Platformio.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Needed a lot of re-formatting, so also added notes on using PlatformIO within Visual Studio Code. Now published at http://marlinfw.org/docs/basics/install_arm.html

**Comment by ModMike** [comment]
Very cool, what tool did you use for formatting? 

First time I do this.

**Comment by thinkyhead** [comment]
The `.md` files in this repo are "GitHub Flavored Markdown" (GFM) embedded in `.yml`, so I just used the **MarkdownEditing** plugin in **Sublime Text 3** with the **Markdown GFM** syntax selected. I used an installation of **Jekyll** on my laptop running its built-in http server to preview the site at localhost:4000 while editing it.

**Comment by ModMike** [comment]
Thank you for the info.  I am on a Mac so I used Macdown which is apparently not Github flavoured, or I simply didn't use it right.  I did install Gems and Jekyll though.

I didn't realize attribution was not permitted on Github, I will make sure to not put my name.  Again first contribution error so bear with me as I learn.

**Comment by thinkyhead** [comment]
I also use macOS. I find that Sublime Text 3 with plugins meets pretty much all my coding needs!

> I didn't realize attribution was not permitted on Github

Actually, pages on the website do get attribution. You'll see that your icon and a link to your GitHub home-page is shown at the top-right of the article page. You should upload a nice image of yourself or your logo to GitHub and it will appear there!

**Comment by ModMike** [comment]
I updated my profile with an icon and such.  How do I get credit?  I worked hard on that original article and I don’t even have contributor status.

Michael Triffon

**Comment by thinkyhead** [comment]
@ModMike — You're the author:

image

**Comment by ModMike** [comment]
Hi Scott,

I am turning to you in desperation.  I understand you receive an Ender 3 and hope you can help.

I replaced the Creality Ender 3 contoroller with my rearm ramps setup and everything seems to work except the G29 command, but thats not my primary issue.

I am trying to figure out how to use the Creality single cable display to connect to the ramps.  I can’t seem to find any pinouts for the 12864ZW-10 display.  I did look at the Panucatt support page and have their split cable and the smart adapter.  I would like to use the original display to keep the stock look of the printer.  

Can you help me or direct me to a resource?  I’ve been on this for 5 hours and am going crazy.  

Thanks!

Michael Triffon

**Comment by thinkyhead** [comment]
> I am turning to you in desperation.  I understand you receive an Ender 3 and hope you can help.

I have a pair of CR-10S units, but no Ender 3. I'm not too familiar with its single-cable display connector. All I know is that we can use `CR10_STOCK_DISPLAY` with RAMPS. The RAMPS pins file assigns these AUX3 / AUX4 pins for it, which probably pass through on the common RAMPS graphical display adapter.

```cpp
    #if ENABLED(CR10_STOCKDISPLAY)

      #define LCD_PINS_RS       27
      #define LCD_PINS_ENABLE   29
      #define LCD_PINS_D4       25

      #if DISABLED(NEWPANEL)
        #define BEEPER_PIN      37
      #endif

      #if ENABLED(CR10_STOCKDISPLAY)
        #define BTN_EN1         17
        #define BTN_EN2         23
      #else
        . . .
      #endif

      #define BTN_ENC           35
      #define SD_DETECT_PIN     49
      #define KILL_PIN          41
```

image

**Comment by ModMike** [comment]
thinkyhead,

Thank you for jumping in, I have seen your work on LCD configs and hope you will be able to shed some light on the Creality LCD.

The CR-10 and Ender 3 display seem to be identical.  From what I have seen on line, the CR-10 display (at least the current ones) have EXP1 EXP2 and EXP 3 headers, with EXP3 being the only populated one.  The only slight difference is that the Creality LCD that came with my Ender 3 has all 3 populated, even though we only use EXP3, which is connected to EXP1 on the Reality Melzo 1284p controller.

I did look at the CR-10 Stock display file before.  For testing purposes, I used the REPRAP_SMART_GRAPHICS on my Creality Melzi board that had Marlin 2.0.X bug fix installed and it ran/runs perfectly, leading me to believe that the LCD pinout is identical to Rerap displays.

I suspect that they combined parts of EXP1 and EXP2 because the SD card is not on the display, allowing them to use a single cable on the EXP3 header.  The issue I have is that I don't have a pinout of the physical header so I don't know what pins they are equal to.

I suspect I am really just not understanding this properly and going about it the right way.  Could you point me in the right direction?

Thank you.

**Comment by ModMike** [comment]
Update:

I found a silkscreen under the black tape covering the header pins.  The one next to EXP3 has the following notation:

Pin 3 E
Pin 7 RW
Pin 8 A0
Pin 9 VD
Pin 10 VS

I used a voltmeter to trace all the EXP3 pins and if my theory is correct and I did this properly I get:

Pin 1 = Beep
Pin 2 = SEC
Pin 3 = SE2
PIN 4 - N/C
Pin 5 = SE1
Pin 6 = LCD4
Pin 7 = LCDR
PIN 8 = LCD E
Pin 9 = GND
Pin 10 = VCC

The only pin missing is LCD 6.  

Is this all that is needed to run a 12864 LCD and encoder?

**Comment by ModMike** [comment]
Ok so all figured out.

After carefully mapping the pins, I simply rotated the EXP1 and EXP2 cages on the motherboard 180 degrees.  Be careful when lifting them off, they are very tight and you dont want to damage the board.  I used an exacto to start them and then a small flat blade screwdriver to pry them up.

I used the split cable from re-arm (to get 5 volts), plugged it all in and it worked like a charm.  Step 2 would be to define the re-arm J3 pins so I can use one cable and do away with the smart adapter.

**Comment by ModMike** [comment]
Step 2 complete.  We can now use a CR-10 single cable plugged in to the Creality LCD display EXP3 port and the re-arm JP3 header with a  standard straight cable.  No need for a ramps smart adapter or special split cable.

Add the following to the pins_RAMPS_RE_ARM.h after the last LCD display:

#if ENABLED(CR10_STOCKDISPLAY)

  #define BEEPER_PIN         P2_11 

  #define BTN_EN1               P0_16  
  #define BTN_EN2              P1_23 
  #define BTN_ENC              P3_25 

  #define LCD_PINS_RS         P0_15 
  #define LCD_SDSS              P0_15  
  #define LCD_BACKLIGHT_PIN   P0_15  
  #define LCD_PINS_ENABLE     P0_18
  #define LCD_PINS_D4         P2_06 
#endif

I will clean it up and add comments.  What else do I need to do to get it ready for a pull request?  I ask because I never did this before

**Comment by thinkyhead** [comment]
Congratulations on figuring out the pinouts. I look forward to your pull request.

- https://help.github.com/articles/creating-a-pull-request/
- http://marlinfw.org/docs/development/getting_started_pull_requests.html

**Comment by ModMike** [comment]
Just finished cleaning it up and will prepare the pull request.  

The one thing that eludes me is encoder direction.  I tried swapping EN1 and EN2 but it just freezes.  I used #define REVERSE_ENCODER_DIRECTION and that works perfect.  Any tips or thats just the way it has to be?

**Comment by ModMike** [comment]
Pull request created.  I had a few false starts but hope I got it right and didn't offend anyone.

**Comment by thinkyhead** [comment]
> I tried swapping EN1 and EN2 but it just freezes.

Yeah, that won't work because of how encoders are implemented. So just use `REVERSE_ENCODER_DIRECTION`.

**Comment by ModMike** [comment]
That’s what I ended up doing.

**Pull request merged**
