### PR TITLE
📝 Black Pill / I3DBEEZ9 Boards

### PR DESCRIPTION
**Pull request by thisiskeithb**
Add latest boards.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I like that we have access to update the boards list now, but I'm still thinking this could be automated. Perhaps pulling a copy of upstream `boards.h` and parsing it on deployment?

I'll have to get this building locally and see what can be scripted through GitHub Actions.

**Comment by thisiskeithb** [comment]
Committed directly: https://github.com/MarlinFirmware/MarlinDocumentation/commit/52b43fd0557a1cd6757a0d1d8e25a0e17c4eef74

**Comment by thinkyhead** [comment]
> I like that we have access to update the boards list now, but I'm still thinking this could be automated.

Automation is certainly possible, but I haven't gotten around to it with all the other junk I need to attend to. My strategy meanwhile is to occasionally look at the commit history of `boards.h` in reverse chronological order and add boards until I reach the last one that was already added.

**Comment by thisiskeithb** [comment]
> My strategy meanwhile is to occasionally look at the commit history of `boards.h` in reverse chronological order and add boards until I reach the last one that was already added.

As someone who frequently adds boards & deals with pins files a lot, I don’t have a problem with submitting PRs like I’ve done in https://github.com/MarlinFirmware/MarlinDocumentation/pull/514.

**Comment by thinkyhead** [comment]
You don't need to go to so much trouble. This is something I will do in the general course and certainly at the time of any tagged release.

**Pull request closed without merging**
