### PR TITLE
Update lin_advance doc

### PR DESCRIPTION
**Pull request by Sineos**
A take on improving the lin_advance documentation.

@thinkyhead @Sebastianv650 please review.

### CODE REVIEW

**Comment by Sebastianv650** [comment]
I will have a look at the changes tomorow.

**Comment by Sebastianv650** [comment]
That's definitly an improvement!

Some comments from my side:
- The image explaining the printed test pattern: There are two vertical lines above the test pattern. Are they printed, what's their purpose?
- My first intention when reading was that "Considerations before using Linear Advance" section should be above the calibration part. But there is a logic behind it, I think you did that because the calibration is done without the slicer using the pattern generator up to this point so it's fine as is.
- You write that geared extruders have a higher K value than direct drive ones. How do you come to this conclusion? Basicaly there shouldn't be a difference as the "free length" between hobbed bolt and nozzle isn't changed. Also backlash shouldn't change K, but it may introduce effects that can lead to wrong K numbers during calibration.
- "The extruder's steps/mm value has to be calibrated precisely." At low extrusion speeds, to avoid impacts due to nozzle pressure or slipping in the hobbed bolt. Maybe this information could be useful.

**Comment by Sineos** [comment]
> That's definitly an improvement!

Many thanks for your review and comments. 
> The image explaining the printed test pattern: There are two vertical lines above the test pattern. Are they printed, what's their purpose?

They are printed and the idea is to mark the point where the speed changes from slow to fast. I'll add a comment to make clear that they a reference marking of the speed change.
 

> My first intention when reading was that "Considerations before using Linear Advance" section should be above the calibration part. But there is a logic behind it, I think you did that because the calibration is done without the slicer using the pattern generator up to this point so it's fine as is.

Exactly. These considerations mainly aim at production and slicer settings.

> You write that geared extruders have a higher K value than direct drive ones. How do you come to this conclusion? Basicaly there shouldn't be a difference as the "free length" between hobbed bolt and nozzle isn't changed. Also backlash shouldn't change K, but it may introduce effects that can lead to wrong K numbers during calibration.

The reasoning behind this is:
- Gears have backlash
- Backlash adds to the K-Factor, i.e. visually I choose another line as best matching compared to no backlash
- Backlash is assumed constant in calibration as well as in production

If this reasoning is wrong, I'll modify the text.

> "The extruder's steps/mm value has to be calibrated precisely." At low extrusion speeds, to avoid impacts due to nozzle pressure or slipping in the hobbed bolt. Maybe this information could be useful.

I'll add this.

**Comment by Sineos** [comment]
I have been again thinking through the backlash topic:
- Backlash only occurs when starting movement or changing movement direction
- Once in a continuous forward feed, backlash should play no role, thus backlash should be irrelevant on speed changes
- Backlash cannot be accounted for with the calibration test pattern as it would require a full stop and not only a speed change
- When taking backlash into consideration we would need two different K-Factors: One to represent a stop / start or retract / de-retract (whats the opposite of retract?) condition and a different one to represent the speed change condition  

If you agree, I will remove the notion of backlash being a contributor completely

**Comment by Sebastianv650** [comment]
> Once in a continuous forward feed, backlash should play no role, thus backlash should be irrelevant on speed changes

That's the point. As LIN_ADVANCE is only active during printing moves (retract / prime moves are not printing moves), backlash is not relevant. Backlash in the extruder should be only noticeable for rectraction settings.

> (whats the opposite of retract?)

I was asking the same questions some month ago in the Slic3r branch :-D A word that isn't needed much.. Back then we came to the conclusion "prime" would be the best term.

**Comment by Sineos** [comment]
I have reworked the backlash item. I left the sentence about minimizing the backlash because it can lead to strange noises from the extruder due to the pressure control. You had it in your initial version as well and minimizing it surely never hurts.

**Comment by Sebastianv650** [comment]
Thats' fine!

**Comment by Sebastianv650** [comment]
I just used your code generator the first time to dial in K for nGen, it makes calibration incredible quick! Good work :)

**Comment by Sineos** [comment]
Thanks for the positive feedback.

I'm a big fan of open source but unfortunately not much of a software developer. So I'm happy when I can contribute something back.

**Comment by Sineos** [comment]
Squashed the commits. I hope correctly, this is the first time I try this:
```
git rebase -i HEAD~7
git push origin lin_advance --force
```
Any hint on the correct procedure would be welcome, if this was crap.

@Sebastianv650 approved the changes.

Ready to merge from my side.

**Comment by thinkyhead** [comment]
Merged, thanks immensely!

**Pull request merged**
