### PR TITLE
Improved docs

### PR DESCRIPTION
**Pull request by chepo92**
added some files, moved some text, starting HAL documentation

### CODE REVIEW

**Comment by chepo92** [comment]
Why is it failing? 
jekyll 3.8.5 | Error:  Permission denied @ rb_sysopen - /srv/jekyll/build/sitemap.xml ?

**Comment by shitcreek** [comment]
I can't remember what I did the last time I had that issue. Let's see if @thinkyhead knows what's up.
There is a temp folder for work in progress files - I'd stick the incomplete files there.

**Comment by chepo92** [comment]
> 
> 
> There is a temp folder for work in progress files - I'd stick the incomplete files there.

Nice to know, we also should document that :D 

I'll move them there then

**Comment by chepo92** [comment]
@shitcreek , @thinkyhead , 
moved and splitted uncomplete files
Jekyll CI build continues failling, 
I see there are recent merges done even with this fail anyway

**Comment by thinkyhead** [comment]
Thanks a lot!

**Pull request merged**
