### PR TITLE
Input shaping calibration pattern

### PR DESCRIPTION
**Pull request by KimmoHop**
Input shaping calibration pattern from **tombrazier** converted from Python to JS + page for Marlin Documentation.

FR: https://github.com/MarlinFirmware/Marlin/issues/26166

More instructions to interpret results + images from X and Y damping factor are needed.

Calibration page uses same styles as K-factor calibration page (because it's shameless copy), adding new styles to its own file, when needed.

### CODE REVIEW

**Comment by dbuezas** [comment]
Very cool!
The speed at which the bed is risen doesn't respect the travel speed set int UI 
It is like this regardless of the UI setting (I had it set to 1000)
```
G1 Z10 F100; Z raise
```

100 looks hilariously slow :)

**Comment by KimmoHop** [comment]
> G1 Z10 F100; Z raise
> ```
> 
> 100 looks hilariously slow :)

It does take a while to end :D It should be x60 (mm/s vs mm/min) :/

Another thing that came to my mind is clearing gcode when starting generating & not allowing saving empty (or worse - old) files in case of error. + syntax things, though I'm happy how it turned out overall :)

**Comment by dbuezas** [comment]
Yeah, it's taking shape very nicely, congrats!
Teo things that cought me off guard (I'm new to marlin 2 and all these shananigans) is that I had to disable linear advance and max out joint deviation for this to work well  I'm still unsure what the damping does or how to interprete the results. I ended up making a ringing tower swiping zeta, which to my surprise threw the vest results at zeta=0.
A sentence about this in the docs may help newbies like me :)

**Comment by KimmoHop** [comment]
> * I had to disable linear advance

Code has M900 K0 at the beginning (and reloads good values from eeprom at the end). Does it not work? Do you have Klipper?

> * And also max out joint deviation

Code has M205 J0.3 (from original python script) for frequency sweeps. Is that a little or a lot?

> * I'm still unsure what the damping does or how to interprete the results. I ended up making a ringing tower swiping zeta, which to my surprise threw the vest results at zeta=0.
> 
> A sentence about these in the docs may help newbies like me :)

We are in the same boat ;) I guess the line in the pattern that is most uniform, is the correct. Damping frequencies must be set before zeta calibration. My zeta print for X is committed as a base, though not to be trusted even by me.

My zeta print for Y looked like this, not very easy to read :D
image

**Comment by dbuezas** [comment]
Oh my mistake, I made so many tests woth this and the ringing tower that I mixed things up:
* Linear advance is disabled correctly
* Junction deviation at 0.3 is it's max, which keeps accelerations high (also correct)

This test was way more clear than the towers for frequency. Regarding zeta, i went for the ringing tower and zeta = 0 looked best, which I don't understand, so 🤷 .
A suggestion/request:  to draw a ruler and the axis (x/y)  before each of the frequency patterns (like PA calibrations do)

**Comment by thinkyhead** [comment]
> "Printer may skip layers at or above the resonant frequency."

This is probably confusing. Whole layers can't be skipped. That makes a mess. What does this really mean? Please rephrase.

**Comment by KimmoHop** [comment]
> > "Printer may skip layers at or above the resonant frequency."
> 
> This is probably confusing. Whole layers can't be skipped. That makes a mess. What does this really mean? Please rephrase.

True + pattern is single layer. I'll fix that. On Marlin side issue I'm waiting better instructions how to interpret results.

**Comment by KimmoHop** [comment]
I will print new patterns and scan or shoot them properly + draw images for "theory" section

**Comment by thinkyhead** [comment]
I went ahead and did further cleanup on this and the K-factor code to make it a bit smaller and (theoretically) easier to extend by using more arrays of element names and matching dictionary keys to field names. Everything still seems to work fine in my local Jekyll, but please check that it's still generating good G-code.

**Comment by KimmoHop** [comment]
I created another PR for TODO images https://github.com/MarlinFirmware/MarlinDocumentation/pull/528/files

**Pull request merged**
