### PR TITLE
UBL getting started guide - first pass

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
Per request I'm putting the guide on the wiki knowing that we'll be updating/correcting it soon.

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
The failing checks are all on files not associated with this change.

**Comment by Bob-the-Kuhn** [comment]
@thinkhead - I need your help.  Please move this change into the wiki.  I tried doing it myself but gave up after 2 days.

----

I'm stuck at a nokogiri problem with the "bundle exec jekyll build --profile --trace --no-watch" command.

The gem compiles by itself but not when within the bundle.  

I'm using the Ubuntu module within Windows10.  Definitely a different world for me.  As usual with beginners I can show you lots of ways to get it wrong.  I was able to get the test server running before I tried to run the script and ran into the problem.

**Comment by Roxy-3D** [comment]
Just as an FYI:   at: http://forums.reprap.org/read.php?415,766335   these people need more hand holding than we are giving them.      I wonder if we need a high level description of the different parts of the system, and then a few paragraphs how everything fits together.    And then...   a quick start bullet point list of things to do? 

I don't know the answer....

**Comment by Bob-the-Kuhn** [comment]
Question - I couldn't find a HTMLPROOFER so I used the Ruby HTML-PROOFER.  Is that the correct one?

I've gotten by the nokogiri problem and almost to the end of the script.

Here's the text from the end of the script.  Either I don't have the privileges to write to gh-pages or the script has a bug.

sent 23,659,233 bytes  received 5,761 bytes  3,640,768.31 bytes/sec
total size is 23,635,701  speedup is 1.00
HEAD is now at f90933c Trying to fix some broken links
error: pathspec 'gh-pages' did not match any file(s) known to git.


FYI - you need to commit your changes before running the script or git desktop will restore the original files. just before the HTML-Proofer runs.  I took me a while to figure out why my corrections for the HTML-Proofer's complaints kept disappearing.

**Comment by Bob-the-Kuhn** [comment]
Scott just re-built the wiki so the getting started guide is now visible to everyone.

**Pull request merged**
