### PR TITLE
Major website redesign

### PR DESCRIPTION
**Pull request by jbrazio**

### CODE REVIEW

**Comment by thinkyhead** [comment]
I look forward to seeing it in action!

I noticed that the tag line on the site is "The best 3D printer firmware." I wish it were so! Can we change that to something like "The most widely-used 3D printer firmware in the world," or something like that. I think that would be accurate!

**Comment by jbrazio** [comment]
I've changed it @thinkyhead.
See the new frontpage http://www.marlinfw.org/

**Comment by thinkyhead** [comment]
The redesign is looking very nice. I have a feeling that "The firmware we all trust" is going to make some people scoff a little, because Marlin has always been _a little bit_ broken. I'm trying to think of some things we can say that are positive about Marlin but not too hyperbolic or self-aggrandizing… dare I say, humble… or maybe just more ephemeral…

##### "Printing the planet, one layer at a time."
##### "The journey of 1000 millimeters begins with a single step."

**Comment by thinkyhead** [comment]
Whew, I could edit the configuration page all day….

**Comment by Roxy-3D** [comment]
Marlin is trusted by the users.      Of course there are some bugs.     But
remember, this is the RepRap community.   Most of these printers are
assembled as kits and the people doing that know they will have to work
through a few issues.

Ask yourself this question:   Why do most 3D-Printer kits ship with Marlin
pre-loaded on the controller board?    The Answer is the Vendor thinks that
makes sense.   Probably the Vendor trusts Marlin.    Who knows?   Maybe the
Vendor's think Marlin is the best.

I'm pretty sure the Vendor's are not loading Marlin because they don't
trust it.   And they are not loading it because they want their Printer
Kits to fail and be hated by everybody.

**Comment by jbrazio** [comment]
We need a digest of that.. Currently that page is the same thing than documentation.h.. which means double work to update.

We need visuals, I can't agree more with you on this one Scott.

**Comment by thinkyhead** [comment]
The ultimate automated solution would be to strictly use Doxygen comments in the configurations, write concise summaries of each option there, and include links to the high-level topics at marlinfw.org that discuss them more. We should then use Doxygen or a custom script to produce Jekyll-friendly output.

**Pull request merged**
