### PR TITLE
Auto build doc update - replaces PR #169

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
1. Add images to **install_platformio.md** and add items to the ADVANCED section
2. Add CLI and VS code documentation - these are separate pages linked from the **install_platformio.md** page

---

This PR is at the **needs review** stage.  I'm especially looking for omissions  of subject areas and skipped steps.

**TO DO LIST:**
1. ~add Sublime section~
2. ~verify links and command lines~
3. wait for feedback
4. incorporate feedback

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'll push it from my local copy, which is pretty recent.

**Comment by thinkyhead** [comment]
A quick look, and it seems to be okay. Upstream matches my working copy.

**Comment by Bob-the-Kuhn** [comment]
No hurry.  Things have been "interesting".  I'm having problem with Sublime and TCL version issues.  It'll be a day or two before I can add Sublime to this PR.

**Comment by Bob-the-Kuhn** [comment]
I've just finished the first pass.  All the substance that I wanted has been included.

Now to see if it makes sense to others.

**Comment by Bob-the-Kuhn** [comment]
I've removed the TBDs in the directory paths for Sublime and VScode.

I have no more changes.  It's 100% ready for review.

**Pull request merged**
