### PR TITLE
update G29 Ubl example

### PR DESCRIPTION
**Pull request by Vertabreak**
attempt to better explain and simplify how to use UBL.

### CODE REVIEW

**Comment by shitcreek** [comment]
A few things:
I think "G29 P2 B T... Manual probing..." should be kept in there.
Line 339 needs another comma or broken up like so: "Produce mesh validation pattern with primed nozzle. G26 is optional; any bed leveling stl would also work."
I think `G29 J` should be kept and rewritten something like, "Probe the specifies 3 points and tilt mesh according to findings. Use `G29 J2` to probe 4 corners instead.

**Comment by Vertabreak** [comment]
the example is intended to be the minimum required to setup.
i never once even used any of the g29 p2 functions they where never needed.
i did tweak the wording a bit

**Comment by Vertabreak** [comment]
made some adjustments based on feed back.

**Comment by shitcreek** [comment]
I think as part of a documentation, we should list as much information as possible wether the feature is ever used or not.
I think `G29 P2` should be worded a bit differently because it probes unreachable points, and it requires an LCD controller.
It should be noted somewhere that you can get more detail by checking the comment section of `ubl_G29.cpp` file - this goes for all other pages as well with their corresponding files.

**Comment by shitcreek** [comment]
A video demo would be a great idea!

**Comment by Vertabreak** [comment]
i added P2 in the optional settings so it is there.

**Comment by Vertabreak** [comment]
made further adjustments based on feedback.

**Comment by Vertabreak** [comment]
once i get everything setup for recording again ill do a demo video for basic ubl setup. 
gotta get my octoprint webcam stuff all sorted so i can show sending of commands and printer moving with voice over.
might even tack of how to add a custom command to one click setup UBL with a probe or manual i had these all setup on my fork before. it might be cool to just add a 1 click setup menu entry for both directly to the menu in marlin making most of this obsolete.

**Pull request merged**
