### PR TITLE
Fix jekyll ci attempt2

### PR DESCRIPTION
**Pull request by chepo92**
Using this: https://github.com/kinnetica/jekyll-plugins/issues/6

### CODE REVIEW

**Comment by chepo92** [comment]
Well that is a pass, now to blame feeds file

**Comment by thinkyhead** [comment]
It looks like this change would break the deployment.

**Comment by thinkyhead** [comment]
See https://github.com/envygeeks/jekyll-docker#readme for additional tips that might resolve the build issues.

Interestingly, the `jekyll-pub` action (https://github.com/BryanSchuetz/jekyll-deploy-gh-pages) doesn't have any such errors. However, it always publishes some earlier point in time instead of the latest commit, so it can't be used as it is.

**Comment by chepo92** [comment]
> 
> 
> It looks like this change would break the deployment.
@thinkyhead 
What you mean with deployment (I'm still not very familiar with terminology, but always learning)? the jekyll CI build failing? if it is that, it never worked for any PR after #263, I thought it was a problem from sitemap plugin (and this fixes it) but also this shows that it's not the only problem

II'l check your links.

**Comment by thinkyhead** [comment]
> What you mean with deployment

Your modification is changing the location where the sitemap is written. That might eliminate the error when doing a Jekyll-build for testing. But if that change is left in, it will also cause the sitemap file to be written to the wrong location when the site is deployed.

**Pull request closed without merging**
